from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Channel(Protocol):
    name: str

    def build_inbound(self, *, user_id: str, text: str, session_id: str | None = None, metadata: dict[str, Any] | None = None) -> Any: ...
    def deliver(self, reply: Any) -> Any: ...


@runtime_checkable
class SessionStore(Protocol):
    def create_session(self, channel: str, user_id: str) -> Any: ...
    def find_latest_session(self, channel: str, user_id: str) -> Any: ...
    def get_session(self, session_id: str) -> Any: ...
    def add_message(self, session_id: str, role: str, content: Any) -> Any: ...


@runtime_checkable
class Memory(Protocol):
    def wake_memory(self, *args: Any, **kwargs: Any) -> Any: ...
    def inspect_memory_health(self, *args: Any, **kwargs: Any) -> Any: ...


@runtime_checkable
class ToolRegistryPort(Protocol):
    def register(self, name: str, func: Any, description: str = "", **kwargs: Any) -> None: ...
    def get(self, name: str) -> Any: ...


@runtime_checkable
class SchedulerPort(Protocol):
    def run_due(self, *, now: str | None = None) -> Any: ...
    def schedule(self, session_id: str, text: str, **kwargs: Any) -> Any: ...


@runtime_checkable
class AgentRuntime(Protocol):
    state: SessionStore

    def run_turn(self, session_id: str, text: str, **kwargs: Any) -> dict[str, Any]: ...
    def run_task(self, session_id: str, text: str, **kwargs: Any) -> dict[str, Any]: ...
    def get_or_create_session(self, *, channel: str, user_id: str) -> Any: ...
